# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('sinopsis', models.TextField()),
                ('director', models.CharField(max_length=140)),
                ('fecha_estreno', models.DateField()),
            ],
        ),
    ]
